backend:
  name: git-gateway
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - name: 'Hero'
    label: 'Hero'
    folder: 'content'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Button', name: 'button', widget: 'string' }
      - { label: 'Featured Video', name: 'video', widget: 'video' }
