backend:
  name: git-gateway
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - label: 'content'
    name: 'content'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'content/index.md'
        create: false
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Button', name: 'button', widget: 'string' }
          - { label: 'Featured Video', name: 'video', widget: 'string' }
          - label: Images
            name: images
            widget: list
            fields:
              - { label: 'Alt Text', name: 'alt', widget: 'string' }
              - {
                  label: 'Image',
                  name: 'alt',
                  widget: 'image',
                  media_library: { config: { multiple: true } }
                }
          - label: 'Photo 1'
            name: 'photo1'
            widget: 'image'
            allow_multiple: true
            media_library:
              config:
                multiple: true
          - label: 'Photo 2'
            name: 'photo2'
            widget: 'image'
            allow_multiple: true
            media_library:
              config:
                multiple: true
          - label: 'Photo 3'
            name: 'photo3'
            widget: 'image'
            allow_multiple: true
            media_library:
              config:
                multiple: true
          - label: 'Photo 4'
            name: 'photo4'
            widget: 'image'
            allow_multiple: true
            media_library:
              config:
                multiple: true
          - label: 'Photo 5'
            name: 'photo5'
            widget: 'image'
            allow_multiple: true
            media_library:
              config:
                multiple: true
          - label: 'Photo 6'
            name: 'photo6'
            widget: 'image'
            allow_multiple: true
            media_library:
              config:
                multiple: true
          - label: 'Photo 7'
            name: 'photo7'
            widget: 'image'
            allow_multiple: true
            media_library:
              config:
                multiple: true
          - label: 'Photo 8'
            name: 'photo8'
            widget: 'image'
            allow_multiple: true
            media_library:
              config:
                multiple: true
          - label: 'Photo 9'
            name: 'photo9'
            widget: 'image'
            allow_multiple: true
            media_library:
              config:
                multiple: true
      - label: 'About Page'
        name: 'about'
        file: 'content/about.md'
        create: false
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - label: Members
            name: members
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Role, name: role, widget: string }
      - label: 'Bands We Cover Page'
        name: 'about'
        file: 'content/bands-we-cover.md'
        create: false
        fields:
          - { label: 'Description', name: 'description', widget: 'string' }
          - label: Bands
            name: bands
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
      - label: 'Upcoming Shows Page'
        name: 'upcoming-shows'
        file: 'content/upcoming-shows.md'
        create: false
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - label: Shows
            name: shows
            widget: list
            fields:
              - { label: Venue, name: venue, widget: string }
              - { label: Address, name: address, widget: string }
              - { label: Date, name: date, widget: date }
